title: wiki
description: ->
  A personal wiki.

collections:
  articles:
    output: true
    permalink: /:path

defaults:
  -
    scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
